### ISSUE TITLE
会开放"OPENTHOS 2.x.x (multiwindow-nougat)"的源码吗

### ISSUE THREAD

**Issue by baiyunping333** [openthos/OTO#5]
会开放"OPENTHOS 2.x.x (multiwindow-nougat)"的源码吗？对这个项目很有兴趣。

**Comment by faxiang1230** [comment]
建议直接发送给OPENTHOS组陈老师邮件:yuchen@mail.tsinghua.edu.cn,在OPENTHOS中不以github issue作为问题讨论，而是直接以邮件来讨论的.

**Comment by baiyunping333** [comment]
太感谢了
